package com.kaaneneskpc.cointy.core.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.staticCompositionLocalOf
import com.kaaneneskpc.cointy.settings.domain.model.Language

data class StringResources(
    val settings: String,
    val profile: String,
    val editProfile: String,
    val firstName: String,
    val lastName: String,
    val save: String,
    val cancel: String,
    val appearance: String,
    val systemDefault: String,
    val followSystemTheme: String,
    val lightMode: String,
    val alwaysLightTheme: String,
    val darkMode: String,
    val alwaysDarkTheme: String,
    val language: String,
    val selectLanguage: String,
    val currency: String,
    val selectCurrency: String,
    val notifications: String,
    val enableNotifications: String,
    val priceAlerts: String,
    val getPriceAlertNotifications: String,
    val about: String,
    val version: String,
    val termsOfService: String,
    val privacyPolicy: String,
    val rateApp: String,
    val portfolio: String,
    val totalValue: String,
    val cashBalance: String,
    val discoverCoins: String,
    val history: String,
    val analytics: String,
    val alerts: String,
    val buy: String,
    val sell: String,
    val availableBalance: String,
    val amountOwned: String,
    val transactionHistory: String,
    val noTransactions: String,
    val back: String,
    val general: String,
    val preferences: String,
    val tapToEdit: String,
    val profileUpdated: String,
    val enterFirstName: String,
    val enterLastName: String,
    val exportData: String,
    val exportPortfolio: String,
    val exportFormat: String,
    val exportCsv: String,
    val exportJson: String,
    val exportButton: String,
    val exportSuccess: String,
    val exportError: String,
    val exportPreview: String,
    val exportCoinsCount: String,
    val exportTransactionsCount: String,
    val exportFileSaved: String,
    val exportSelectFormat: String,
    val welcomeToCointy: String,
    val welcomeDescription: String,
    val virtualBalanceTitle: String,
    val virtualBalanceDescription: String,
    val portfolioManagementTitle: String,
    val portfolioManagementDescription: String,
    val getStarted: String,
    val next: String,
    val skip: String,
    val totalPortfolioValue: String,
    val yourAssets: String,
    val coin: String,
    val coins: String,
    val portfolioEmpty: String,
    val portfolioEmptyDescription: String,
    val discoverAndBuyCoins: String,
    val export: String,
    val transaction: String,
    val transactions: String,
    val searchTransactions: String,
    val all: String,
    val buyOnly: String,
    val sellOnly: String,
    val sortNewest: String,
    val sortOldest: String,
    val sortAmountDesc: String,
    val sortAmountAsc: String,
    val sort: String,
    val noResultsFound: String,
    val tryAdjustingFilters: String,
    val noTransactionsYet: String,
    val transactionHistoryWillAppear: String,
    val noPriceAlerts: String,
    val priceAlertsDescription: String,
    val alert: String,
    val target: String,
    val triggered: String,
    val created: String,
    val above: String,
    val below: String,
    val addAlert: String,
    val portfolioAnalytics: String,
    val noAnalyticsData: String,
    val noAnalyticsDescription: String,
    val invested: String,
    val totalProfitLoss: String,
    val portfolioDistribution: String,
    val portfolioHistory: String,
    val coinPerformance: String,
    val buyCoin: String,
    val sellCoin: String,
    val enterAmountToBuy: String,
    val enterAmountToSell: String,
    val buyNow: String,
    val sellNow: String,
    val riskAnalysis: String,
    val riskScore: String,
    val riskBreakdown: String,
    val portfolioVolatility: String,
    val diversificationScore: String,
    val concentrationRisk: String,
    val coinRiskContribution: String,
    val noRiskData: String,
    val noRiskDataDescription: String,
    val lowRisk: String,
    val moderateRisk: String,
    val highRisk: String,
    val criticalRisk: String,
    val createAlert: String,
    val currentPrice: String,
    val alertCondition: String,
    val notifyWhenPrice: String,
    val targetPricePlaceholder: String,
    val enterTargetPrice: String,
    val volatilityAlerts: String,
    val volatilityAlertsDescription: String,
    val volatilityThreshold: String,
    // Auth strings
    val login: String,
    val loginDescription: String,
    val register: String,
    val registerDescription: String,
    val email: String,
    val password: String,
    val confirmPassword: String,
    val displayName: String,
    val enterEmail: String,
    val enterPassword: String,
    val enterConfirmPassword: String,
    val enterDisplayName: String,
    val signIn: String,
    val signUp: String,
    val signOut: String,
    val forgotPassword: String,
    val forgotPasswordDescription: String,
    val resetPassword: String,
    val noAccount: String,
    val alreadyHaveAccount: String,
    val emailSent: String,
    val resetEmailSentDescription: String,
    val backToLogin: String
)

val EnglishStrings = StringResources(
    settings = "Settings",
    profile = "Profile",
    editProfile = "Edit Profile",
    firstName = "First Name",
    lastName = "Last Name",
    save = "Save",
    cancel = "Cancel",
    appearance = "Appearance",
    systemDefault = "System Default",
    followSystemTheme = "Follow system theme",
    lightMode = "Light Mode",
    alwaysLightTheme = "Always use light theme",
    darkMode = "Dark Mode",
    alwaysDarkTheme = "Always use dark theme",
    language = "Language",
    selectLanguage = "Select language",
    currency = "Currency",
    selectCurrency = "Select currency",
    notifications = "Notifications",
    enableNotifications = "Enable notifications",
    priceAlerts = "Price Alerts",
    getPriceAlertNotifications = "Get notified when price targets are reached",
    about = "About",
    version = "Version",
    termsOfService = "Terms of Service",
    privacyPolicy = "Privacy Policy",
    rateApp = "Rate App",
    portfolio = "Portfolio",
    totalValue = "Total Value",
    cashBalance = "Cash Balance",
    discoverCoins = "Discover Coins",
    history = "History",
    analytics = "Analytics",
    alerts = "Alerts",
    buy = "Buy",
    sell = "Sell",
    availableBalance = "Available Balance",
    amountOwned = "Amount Owned",
    transactionHistory = "Transaction History",
    noTransactions = "No transactions yet",
    back = "Back",
    general = "General",
    preferences = "Preferences",
    tapToEdit = "Tap to edit",
    profileUpdated = "Profile updated",
    enterFirstName = "Enter first name",
    enterLastName = "Enter last name",
    exportData = "Export Data",
    exportPortfolio = "Export Portfolio",
    exportFormat = "Export Format",
    exportCsv = "CSV",
    exportJson = "JSON",
    exportButton = "Export",
    exportSuccess = "Export Successful",
    exportError = "Export Failed",
    exportPreview = "Export Preview",
    exportCoinsCount = "Portfolio Coins",
    exportTransactionsCount = "Transactions",
    exportFileSaved = "File saved to Downloads",
    exportSelectFormat = "Select export format",
    welcomeToCointy = "Welcome to Cointy",
    welcomeDescription = "Your personal cryptocurrency portfolio tracker and virtual trading simulator.",
    virtualBalanceTitle = "Virtual Balance",
    virtualBalanceDescription = "Start with a virtual cash balance to practice trading without any real risk.",
    portfolioManagementTitle = "Portfolio Management",
    portfolioManagementDescription = "Monitor your holdings, track performance, and analyze your investment history.",
    getStarted = "Get Started",
    next = "Next",
    skip = "Skip",
    totalPortfolioValue = "Total Portfolio Value",
    yourAssets = "Your Assets",
    coin = "coin",
    coins = "coins",
    portfolioEmpty = "Your Portfolio is Empty",
    portfolioEmptyDescription = "Start building your crypto portfolio by discovering and buying coins",
    discoverAndBuyCoins = "Discover & Buy Coins",
    export = "Export",
    transaction = "transaction",
    transactions = "transactions",
    searchTransactions = "Search transactions...",
    all = "All",
    buyOnly = "Buy",
    sellOnly = "Sell",
    sortNewest = "Newest",
    sortOldest = "Oldest",
    sortAmountDesc = "Amount ↓",
    sortAmountAsc = "Amount ↑",
    sort = "Sort",
    noResultsFound = "No Results Found",
    tryAdjustingFilters = "Try adjusting your search or filters",
    noTransactionsYet = "No Transactions Yet",
    transactionHistoryWillAppear = "Your transaction history will appear here once you start buying or selling coins",
    noPriceAlerts = "No Price Alerts",
    priceAlertsDescription = "Set up price alerts to get notified when your favorite coins reach your target price",
    alert = "Alert",
    target = "Target",
    triggered = "Triggered",
    created = "Created",
    above = "Above",
    below = "Below",
    addAlert = "Add Alert",
    portfolioAnalytics = "Portfolio Analytics",
    noAnalyticsData = "No Analytics Data",
    noAnalyticsDescription = "Start investing to see your portfolio analytics and performance charts",
    invested = "Invested",
    totalProfitLoss = "Total Profit/Loss",
    portfolioDistribution = "Portfolio Distribution",
    portfolioHistory = "Portfolio History",
    coinPerformance = "Coin Performance",
    buyCoin = "Buy Coin",
    sellCoin = "Sell Coin",
    enterAmountToBuy = "Enter Amount to Buy",
    enterAmountToSell = "Enter Amount to Sell",
    buyNow = "Buy Now",
    sellNow = "Sell Now",
    riskAnalysis = "Risk Analysis",
    riskScore = "Risk Score",
    riskBreakdown = "Risk Breakdown",
    portfolioVolatility = "Portfolio Volatility",
    diversificationScore = "Diversification Score",
    concentrationRisk = "Concentration Risk",
    coinRiskContribution = "Coin Risk Contribution",
    noRiskData = "No Risk Data",
    noRiskDataDescription = "Start investing to see your portfolio risk analysis",
    lowRisk = "Low Risk",
    moderateRisk = "Moderate",
    highRisk = "High Risk",
    criticalRisk = "Critical",
    createAlert = "Create Alert",
    currentPrice = "Current Price",
    alertCondition = "Alert Condition",
    notifyWhenPrice = "Notify me when price goes",
    targetPricePlaceholder = "Enter target price",
    enterTargetPrice = "Target Price ($)",
    volatilityAlerts = "Price Change Notifications",
    volatilityAlertsDescription = "Get notified when coins move significantly",
    volatilityThreshold = "Threshold",
    // Auth strings
    login = "Login",
    loginDescription = "Sign in to your account to continue",
    register = "Create Account",
    registerDescription = "Create a new account to get started",
    email = "Email",
    password = "Password",
    confirmPassword = "Confirm Password",
    displayName = "Display Name",
    enterEmail = "Enter your email",
    enterPassword = "Enter your password",
    enterConfirmPassword = "Confirm your password",
    enterDisplayName = "Enter your name",
    signIn = "Sign In",
    signUp = "Sign Up",
    signOut = "Sign Out",
    forgotPassword = "Forgot Password?",
    forgotPasswordDescription = "Enter your email and we'll send you a link to reset your password",
    resetPassword = "Reset Password",
    noAccount = "Don't have an account?",
    alreadyHaveAccount = "Already have an account?",
    emailSent = "Email Sent!",
    resetEmailSentDescription = "Check your email for a link to reset your password",
    backToLogin = "Back to Login"
)

val TurkishStrings = StringResources(
    settings = "Ayarlar",
    profile = "Profil",
    editProfile = "Profili Düzenle",
    firstName = "Ad",
    lastName = "Soyad",
    save = "Kaydet",
    cancel = "İptal",
    appearance = "Görünüm",
    systemDefault = "Sistem Varsayılanı",
    followSystemTheme = "Sistem temasını takip et",
    lightMode = "Açık Mod",
    alwaysLightTheme = "Her zaman açık tema kullan",
    darkMode = "Koyu Mod",
    alwaysDarkTheme = "Her zaman koyu tema kullan",
    language = "Dil",
    selectLanguage = "Dil seçin",
    currency = "Para Birimi",
    selectCurrency = "Para birimi seçin",
    notifications = "Bildirimler",
    enableNotifications = "Bildirimleri etkinleştir",
    priceAlerts = "Fiyat Uyarıları",
    getPriceAlertNotifications = "Hedef fiyatlara ulaşıldığında bildirim al",
    about = "Hakkında",
    version = "Sürüm",
    termsOfService = "Kullanım Şartları",
    privacyPolicy = "Gizlilik Politikası",
    rateApp = "Uygulamayı Değerlendir",
    portfolio = "Portföy",
    totalValue = "Toplam Değer",
    cashBalance = "Nakit Bakiye",
    discoverCoins = "Kripto Keşfet",
    history = "Geçmiş",
    analytics = "Analitik",
    alerts = "Uyarılar",
    buy = "Al",
    sell = "Sat",
    availableBalance = "Kullanılabilir Bakiye",
    amountOwned = "Sahip Olunan Miktar",
    transactionHistory = "İşlem Geçmişi",
    noTransactions = "Henüz işlem yok",
    back = "Geri",
    general = "Genel",
    preferences = "Tercihler",
    tapToEdit = "Düzenlemek için dokunun",
    profileUpdated = "Profil güncellendi",
    enterFirstName = "Adınızı girin",
    enterLastName = "Soyadınızı girin",
    exportData = "Veri Dışa Aktar",
    exportPortfolio = "Portföyü Dışa Aktar",
    exportFormat = "Dışa Aktarma Formatı",
    exportCsv = "CSV",
    exportJson = "JSON",
    exportButton = "Dışa Aktar",
    exportSuccess = "Dışa Aktarma Başarılı",
    exportError = "Dışa Aktarma Başarısız",
    exportPreview = "Dışa Aktarma Önizleme",
    exportCoinsCount = "Portföy Coinleri",
    exportTransactionsCount = "İşlemler",
    exportFileSaved = "Dosya İndirilenler'e kaydedildi",
    exportSelectFormat = "Dışa aktarma formatı seçin",
    welcomeToCointy = "Cointy'ye Hoş Geldiniz",
    welcomeDescription = "Kişisel kripto para portföy takipçiniz ve sanal ticaret simülatörünüz.",
    virtualBalanceTitle = "Sanal Bakiye",
    virtualBalanceDescription = "Herhangi bir gerçek risk almadan ticaret pratiği yapmak için sanal bir nakit bakiye ile başlayın.",
    portfolioManagementTitle = "Portföy Yönetimi",
    portfolioManagementDescription = "Varlıklarınızı izleyin, performansı takip edin ve yatırım geçmişinizi analiz edin.",
    getStarted = "Başla",
    next = "İleri",
    skip = "Atla",
    totalPortfolioValue = "Toplam Portföy Değeri",
    yourAssets = "Varlıklarınız",
    coin = "coin",
    coins = "coin",
    portfolioEmpty = "Portföyünüz Boş",
    portfolioEmptyDescription = "Kripto portföyünüzü oluşturmaya başlamak için coinleri keşfedin ve satın alın",
    discoverAndBuyCoins = "Keşfet ve Satın Al",
    export = "Dışa Aktar",
    transaction = "işlem",
    transactions = "işlem",
    searchTransactions = "İşlem ara...",
    all = "Tümü",
    buyOnly = "Alış",
    sellOnly = "Satış",
    sortNewest = "En Yeni",
    sortOldest = "En Eski",
    sortAmountDesc = "Tutar ↓",
    sortAmountAsc = "Tutar ↑",
    sort = "Sırala",
    noResultsFound = "Sonuç Bulunamadı",
    tryAdjustingFilters = "Arama veya filtreleri ayarlamayı deneyin",
    noTransactionsYet = "Henüz İşlem Yok",
    transactionHistoryWillAppear = "Coin almaya veya satmaya başladığınızda işlem geçmişiniz burada görünecek",
    noPriceAlerts = "Fiyat Uyarısı Yok",
    priceAlertsDescription = "Favori coinleriniz hedef fiyata ulaştığında bildirim almak için fiyat uyarıları oluşturun",
    alert = "Uyarı",
    target = "Hedef",
    triggered = "Tetiklendi",
    created = "Oluşturuldu",
    above = "Üstünde",
    below = "Altında",
    addAlert = "Uyarı Ekle",
    portfolioAnalytics = "Portföy Analizi",
    noAnalyticsData = "Analiz Verisi Yok",
    noAnalyticsDescription = "Portföy analizlerinizi ve performans grafiklerinizi görmek için yatırım yapmaya başlayın",
    invested = "Yatırılan",
    totalProfitLoss = "Toplam Kar/Zarar",
    portfolioDistribution = "Portföy Dağılımı",
    portfolioHistory = "Portföy Geçmişi",
    coinPerformance = "Coin Performansı",
    buyCoin = "Coin Al",
    sellCoin = "Coin Sat",
    enterAmountToBuy = "Alınacak Tutarı Girin",
    enterAmountToSell = "Satılacak Tutarı Girin",
    buyNow = "Şimdi Al",
    sellNow = "Şimdi Sat",
    riskAnalysis = "Risk Analizi",
    riskScore = "Risk Skoru",
    riskBreakdown = "Risk Dağılımı",
    portfolioVolatility = "Portföy Volatilitesi",
    diversificationScore = "Çeşitlendirme Skoru",
    concentrationRisk = "Yoğunlaşma Riski",
    coinRiskContribution = "Coin Risk Katkısı",
    noRiskData = "Risk Verisi Yok",
    noRiskDataDescription = "Portföy risk analizinizi görmek için yatırım yapmaya başlayın",
    lowRisk = "Düşük Risk",
    moderateRisk = "Orta",
    highRisk = "Yüksek Risk",
    criticalRisk = "Kritik",
    createAlert = "Uyarı Oluştur",
    currentPrice = "Mevcut Fiyat",
    alertCondition = "Uyarı Koşulu",
    notifyWhenPrice = "Fiyat şu yöne gittiğinde bildir",
    targetPricePlaceholder = "Hedef fiyatı girin",
    enterTargetPrice = "Hedef Fiyat ($)",
    volatilityAlerts = "Fiyat Değişim Bildirimleri",
    volatilityAlertsDescription = "Coinler önemli hareket ettiğinde bildirim al",
    volatilityThreshold = "Eşik Değeri",
    // Auth strings
    login = "Giriş Yap",
    loginDescription = "Devam etmek için hesabınıza giriş yapın",
    register = "Hesap Oluştur",
    registerDescription = "Başlamak için yeni bir hesap oluşturun",
    email = "E-posta",
    password = "Şifre",
    confirmPassword = "Şifre Tekrar",
    displayName = "Ad Soyad",
    enterEmail = "E-posta adresinizi girin",
    enterPassword = "Şifrenizi girin",
    enterConfirmPassword = "Şifrenizi tekrar girin",
    enterDisplayName = "Adınızı girin",
    signIn = "Giriş Yap",
    signUp = "Kayıt Ol",
    signOut = "Çıkış Yap",
    forgotPassword = "Şifremi Unuttum",
    forgotPasswordDescription = "E-posta adresinizi girin, şifrenizi sıfırlamak için size bir bağlantı gönderelim",
    resetPassword = "Şifreyi Sıfırla",
    noAccount = "Hesabınız yok mu?",
    alreadyHaveAccount = "Zaten hesabınız var mı?",
    emailSent = "E-posta Gönderildi!",
    resetEmailSentDescription = "Şifrenizi sıfırlamak için e-postanızı kontrol edin",
    backToLogin = "Girişe Dön"
)

fun getStringResources(language: Language): StringResources {
    return when (language) {
        Language.ENGLISH -> EnglishStrings
        Language.TURKISH -> TurkishStrings
    }
}

val LocalStringResources = staticCompositionLocalOf { EnglishStrings }

@Composable
fun ProvideStringResources(
    language: Language,
    content: @Composable () -> Unit
) {
    val strings = getStringResources(language)
    CompositionLocalProvider(LocalStringResources provides strings) {
        content()
    }
}


